hostapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('hostingportal.urls')),
    url(r'^clients/',include('hostingportal.urls')),
    url(r'^clients/oauth/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^clients/oauth/', include('social_django.urls', namespace='social')),
]

hostingportal/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from . import views
from .form import UserForm

app_name='hosting'
urlpatterns = [
    url(r'^$',views.index,name='index'),


    url(r'^clients/login$',views.login_user,name='login_user'),
    #url(r'^clients/$', auth_views.login, {'template_name': 'hostingportal/login_form.html',
                                         # 'authentication_form':UserForm},name='login_user'),
    url(r'^clients/register$',views.register,name='register'),
    url(r'^clients/logout$',views.logout_user,name='logout_user'),
    url(r'^clients/profile$',views.profile,name='profile'),
    url(r'^clients/profile/update$',views.profile,name='profile-update'),
    url(r'^clients/notifications',views.messages,name='messages'),
    url(r'^clients/domains/', views.search_domain, name='search_domain'),
    url(r'^clients/domains/search/(?P<domain_name>[a-zA_Z]+)', views.check_domian_availability, name='search_domain'),
    url(r'^clients/notifications/(?P<message_id>[0-9]+)$',views.message_detail,name='message-detail'),
    url(r'^clients/mydomains',views.domain_list,name='domain_list'),
    url(r'^clients/validate',views.password,name='validate'),
    url(r'^clients/$',views.portal,name='portal'),
]

hostingportal/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from datetime import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact_address=models.TextField()
    city=models.CharField(max_length=50,blank=True)
    country=models.CharField(max_length=100,blank=True)
    company_name=models.CharField(max_length=200,blank=True)
    telephone=models.CharField(max_length=200,blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()
    def __str__(self):
        return self.user.username+ " : " +self.user.first_name + self.user.last_name



class Package(models.Model):
    name=models.CharField(max_length=30)
    price=models.DecimalField(max_digits=9,decimal_places=2)
    def __str__(self):
        return self.name+":"+self.price

class Subscription(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    package_type=models.ForeignKey(Package,on_delete=models.CASCADE)
    expiry_date=models.DateField()
    activation_date=models.DateTimeField(auto_now=True)
    def is_active(self):
        if self.expiry_date.__lt__(datetime.today().date()):
            return True
        return False

    def __str__(self):

        return self.user.username+ ":"+ self.package_type+ " - "+self.expiry_date

class Transaction(models.Model):
    description=models.CharField(max_length=250)
    user=models.ForeignKey(User,default=1)
    timestamp=models.DateTimeField(auto_now=True)

class Log(models.Model):
    description = models.CharField(max_length=250)
    timestamp=models.TextField(max_length=500)
class Notifications(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    content=models.TextField(blank=True)
    sender=models.CharField(max_length=200)
    is_read=models.BooleanField(default=False)
    timestamp=models.DateTimeField(auto_now=True)

hostingportal/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login,logout
from .form import UserForm,ProfileForm,UpdateForm
from django.forms.models import inlineformset_factory
from .models import User,Profile,Subscription,Notifications
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from social_django.models import UserSocialAuth

MESSAGES_TYPE={'unread':0,'read':1}
# Create your views here.
def index(request):
    return render(request, 'hostingportal/index.html')
def validate(request):

    return render(request, 'hostingportal/login_form.html')

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('hosting:portal')
            else:
                return render(request, 'hostingportal/login_form.html', {'error_message': 'Your account has been disabled', 'form':UserForm})
        else:
            return render(request, 'hostingportal/login_form.html', {'error_message': 'Invalid login', 'form':UserForm})
    return render(request, 'hostingportal/login_form.html', {'form':UserForm})


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'hostingportal/clientportal.html')
    context = {"form": form}
    return render(request, 'hostingportal/login_form.html', context)




def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {"form": form}
    return redirect('hosting:login_user')
def get_messages(request,type):
    users_messages=[]
    if type=='unread':
        users_messages = Notifications.objects.all().filter(user=request.user).filter(is_read=False)
    elif type=='read':
        users_messages = Notifications.objects.all().filter(user=request.user).filter(is_read=True)
    else:
        users_messages = Notifications.objects.all().filter(user=request.user)

    return users_messages

@login_required
def portal(request):
    messages=get_messages(request,MESSAGES_TYPE['unread'])
    return render(request, "hostingportal/clientportal.html", {'messages':messages})
@login_required
def messages(request):
    pass

@login_required
def profile(request):
    # instance = get_object_or_404(User, username=request.user.username)
    # form = UpdateForm(request.POST or None, instance=instance)
    # _user=User.objects.get(username=request.user.username)
    # ProfileInlineFormset = inlineformset_factory(User, Profile,
    #                                              fields=('contact_address', 'city', 'country'))
    # formset=ProfileInlineFormset(instance=instance)
    # context={'user':_user,'form':form,'formset':formset}
    # #return render(request, 'hostingportal/profile.html', context)
    # return render(request,'hostingportal/profile.html',context)


    # querying the User object with pk from url
    user = get_object_or_404(User, username=request.user.username)
    # prepopulate UserProfileForm with retrieved user values from above.
    user_form = UpdateForm(instance=user)
    # The sorcery begins from here, see explanation below
    _u=get_object_or_404(Profile,user=user)
    formset = ProfileForm(instance=_u)
    if request.method == "POST":
        user_form = UpdateForm(request.POST, instance=user)
        if user_form.is_valid():
            created_user = user_form.save(commit=False)
            formset = ProfileForm(request.POST, instance=created_user)
            if formset.is_valid():
                created_user.save()
                formset.save()
                context = {'error_message': 'Profile updated successfully',
                           'form': user_form
                           }

                return render(request, 'hostingportal/profile.html', context)
        else:
            return render(request, "hostingportal/profile.html", {
                "form": user_form,
                "formset": formset,
                'error_message': 'Form not valid'
            })

    return render(request, "hostingportal/profile.html", {
        "form": user_form,
        "formset": formset,
        'error_message': ''
    })

@login_required
def update_profile(request):
    # instanc=get_object_or_404(User,username=request.user.username)
    # form=UpdateForm(request.POST or None,instance=instanc)
    # if form.is_valid():
    #     form.save()
    # else:
    #     return redirect('hosting:profile')

    # querying the User object with pk from url
    user = get_object_or_404(User,username=request.user.username)

    # prepopulate UserProfileForm with retrieved user values from above.
    user_form = UserForm(instance=user)

    # The sorcery begins from here, see explanation below
    ProfileInlineFormset = inlineformset_factory(User, Profile,
                                                 fields=('contact_address', 'city', 'country'))
    formset = ProfileInlineFormset(instance=user)
    if request.method == "POST":
        user_form = UserForm(request.POST,instance=user)
        formset = ProfileInlineFormset(request.POST, instance=user)

        if user_form.is_valid():
            created_user = user_form.save(commit=False)
            formset = ProfileInlineFormset(request.POST, instance=created_user)

            if formset.is_valid():
                created_user.save()
                formset.save()
                context={'error_message':'Profile updated successfully',
                         'form':user_form
                         }

                return render(request,'hostingportal/profile.html',context)

    return render(request, "hostingportal/profile.html", {
        "form": user_form,
        "formset": formset,
        'error_message':''
    })

@login_required
def domain_list(request):
    return render(request, 'hostingportal/domain_list.html')

@login_required
def settings(request):
    user = request.user

    try:
        github_login = user.social_auth.get(provider='github')
    except UserSocialAuth.DoesNotExist:
        github_login = None

    try:
        twitter_login = user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None

    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None

    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

    return render(request, 'core/settings.html', {
        'github_login': github_login,
        'twitter_login': twitter_login,
        'facebook_login': facebook_login,
        'can_disconnect': can_disconnect
    })

@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'hostingportal/password.html', {'form': form})
def message_detail(request):
    pass
def search_domain(request):
    return render(request, 'hostingportal/domain_check.html')
def check_domian_availability(request,_domain):
    if _domain is not None:
        from time import sleep
        import sys
        try:
            import whois
        except ImportError:
            print("ERROR: This script requires the python-whois module to run.")
            print("   You can install it via 'pip install python-whois'")
            sys.exit(0)
        try:
            w = whois.whois(_domain)
            return render(request, 'hostingportal/domain_check.html', {'status': 'Available', 'domain_name':_domain})
        except whois.parser.PywhoisError:
            # Exception means that the domain is free
            return render(request, 'hostingportal/domain_check.html', {'status': 'Taken', 'domain_name': _domain})
    return render(request, 'hostingportal/domain_check.html')

hostingportal/templates/hostingportal/base_clientportal.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
{% load staticfiles %}
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'hostingportal/assets/img/apple-icon.png' %}" />
    <link rel="icon" type="image/png" href="{% static 'hostingportal/assets/img/favicon.png' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}{% endblock %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'hostingportal/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'hostingportal/assets/css/material-dashboard.css' %}" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'hostingportal/assets/css/demo.css' %}" rel="stylesheet" />
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
</head>

<script>
  src="{% static 'hostingportal/js/jquery.js' %}"
</script>

<body>
    <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="{% static 'hostingportal/assets/img/sidebar-1.jpg' %}">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

        Tip 2: you can also add an image using data-image tag
    -->
            <div class="logo">
                <a href="{% url 'hosting:index' %}" class="simple-text">
                    DomainBox
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="{% block dashboard_active %}{% endblock %}">
                        <a href="{% url 'hosting:portal' %}">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li class="{% block profile_active %}{% endblock %}">
                        <a href="{% url 'hosting:profile' %}">
                            <i class="material-icons">person</i>
                            <p>User Profile</p>
                        </a>
                    </li>
                    <li class="{% block search_active %}{% endblock %}">
                        <a href="{% url 'hosting:search_domain' %}">
                            <i class="material-icons">search</i>
                            <p>Buy a domain</p>
                        </a>
                    </li>
                    <li class="{% block subscriptions_active %}{% endblock %}">
                        <a href="{% url 'hosting:domain_list' %}">
                            <i class="material-icons">content_paste</i>
                            <p>My Domains</p>
                        </a>
                    </li>
                    <li class="{% block messages_active %}{% endblock %}">
                        <a href="{% url 'hosting:messages' %}">
                            <i class="material-icons">notifications</i>
                            <p>Notifications</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'hosting:logout_user' %}">
                            <i class="material-icons">exit_to_app</i>
                            <p>Logout</p>
                        </a>
                    </li>


                    <li class="active-pro">
                        <a href="upgrade.html">
                            <i class="material-icons">unarchive</i>
                            <p>Contact Us</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> Hi, {{ request.user }} </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">dashboard</i>
                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="material-icons">notifications</i>
    <span class="notification">{{ messages.count }}</span>
    <p class="hidden-lg hidden-md">Notifications</p>
</a>
    <ul class="dropdown-menu">
        {% for message in messages  %}
            <li>
        <a href="#">{{ message.content }}</a>
            </li>

        {% endfor %}


    </ul>

                            </li>
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">person</i>
                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">
                            <div class="form-group  is-empty">
                                <input type="text" class="form-control" placeholder="Domain Search">
                                <span class="material-input"></span>
                            </div>
                            <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                <i class="material-icons">search</i>
                                <div class="ripple-container"></div>
                            </button>
                        </form>
                    </div>
                </div>
            </nav>
            <div class="content">
                {% block body %}

                {% endblock %}
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="{% url 'hosting:portal' %}">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Contact Us
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Terms and Conditions
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>
                        <a href="{% url 'hosting:portal' %}">Domain Box</a>
                    </p>
                </div>
            </footer>
        </div>
    </div>
</body>
<!--   Core JS Files   -->
{% load staticfiles %}
<script src="{% static 'hostingportal/assets/js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'hostingportal/js/jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'hostingportal/assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'hostingportal/assets/js/material.min.js' %}" type="text/javascript"></script>
<!--  Charts Plugin -->
<script src="{% static 'hostingportal/assets/js/chartist.min.js' %}"></script>
<!--  Dynamic Elements plugin -->
<script src="{% static 'hostingportal/assets/js/arrive.min.js' %}"></script>
<!--  PerfectScrollbar Library -->
<script src="{% static 'hostingportal/assets/js/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'hostingportal/assets/js/bootstrap-notify.js' %}"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="#"></script>
<!-- Material Dashboard javascript methods -->
<script src="{% static 'hostingportal/assets/js/material-dashboard.js' %}"></script>


</html>

hostingportal/templates/hostingportal/domain_check.html
{% extends 'hostingportal/base_clientportal.html' %}

{% block title %}
DomainBox : Search for domains
{% endblock %}
{% block search_active %}
active
{% endblock %}
{% block body %}
    <div class="row">
<div class="col-md-8">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Domain Search</h4>
                                    <p class="category">Enter a domian to check availability </p>
                                </div>
                                <div class="card-content">
                                    <form>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating is-empty">
                                                    <label class="control-label">Adress</label>
                                                    <input type="text" class="form-control">
                                                <span class="material-input"></span></div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary pull-right">Search</button>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
    <div class="col-md-4">
   <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Recent searchs</h4>
                                    <p class="category"></p>
                                </div>
                                <div class="card-content">
                                    <ul>
                                        <a>Search 1</a>
                                        <a>Search 2</a>
                                        <a>Search 3</a>
                                    </ul>
                                </div>
                            </div>
    </div>



</div>
    <div class="row">

    </div>

{% endblock %}

hostingportal/templates/hostingportal/login_form.html
{% extends 'hostingportal/base.html' %}
  {% block title %} Clients Portal : Authenticate {% endblock %}
{% block header %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
 {% endblock %}
{% block body %}
  <div class="logmod">
  <div class="logmod__wrapper">
    <span class="logmod__close">Close</span>
    <div class="logmod__container">
      <ul class="logmod__tabs">
        <li data-tabtar="lgm-2"><a href="#">Login</a></li>
        <li data-tabtar="lgm-1"><a href="#">Sign Up</a></li>
      </ul>
      <div class="logmod__tab-wrapper">
      <div class="logmod__tab lgm-1">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your personal details <strong>to create an acount</strong></span>
        </div>
      <!-- Create User Account -->
        <div class="logmod__form">
         <form class="simform" role="form" action="{% url 'hosting:register' %}" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">Firstname*</label>
                {{ form.first_name }}
              </div>
            </div>
              <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">Lastname*</label>
                {{ form.last_name }}
              </div>
            </div>
             <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">Username*</label>
                {{ form.username }}
              </div>
            </div>
              <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">Email*</label>
               {{ form.email }}
              </div>
            </div>
            <div class="sminputs">
              <div class="input string optional">
                <label class="string optional" for="user-pw">Password *</label>
                {{ form.password }}
              </div>
              <div class="input string optional">
                <label class="string optional" for="user-pw-repeat">Repeat password *</label>
                {{ form.rpassword }}
              </div>
            </div>
            <div class="simform__actions">
                <button class="sumbit">Create Account</button>
              <span class="simform__actions-sidetext">By creating an account you agree to our <a class="special" href="#" target="_blank" role="link">Terms & Privacy</a></span>
            </div> 
          </form>
        </div> 
    <div class="row">
        <div class="col-md-6 con">
            <a href="{% url 'social:begin' 'facebook' %}" class="connect facebook">
              <div class="connect__icon">
                <i class="fa fa-facebook"></i>
              </div>
              <div class="connect__context">
                <span>Sign in with <strong>Facebook</strong></span>
              </div>
            </a>
        </div>
        <div class="col-md-6 con">
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="connect googleplus">
              <div class="connect__icon">
                <i class="fa fa-google-plus"></i>
              </div>
              <div class="connect__context">
                <span>Sign in with <strong>Google+</strong></span>
              </div>
            </a>
        </div>
        </div>
      </div>
      <div class="logmod__tab lgm-2">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your email and password <strong>to sign in</strong></span>
              {% if error_message %}
            <p>{{ error_message }}</p>
            {% endif %}
        </div>

          <!-- Sign in -->
        <div class="logmod__form">

          <form accept-charset="utf-8" action="{% url 'hosting:login_user' %}" class="simform" method="post" enctype="multipart/form-data">
              {% csrf_token %}
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">Email*</label>
                {{ form.username }}
              </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-pw">Password *</label>
                {{ form.password }}
                						<span class="hide-password">Show</span>
              </div>
            </div>
            <div class="simform__actions">
                <button class="sumbit">Log In</button>
              <span class="simform__actions-sidetext"><a class="special" role="link" href="#">Forgot your password?<br>Click here</a></span>
            </div> 
          </form>
        </div>
    <div class="row">
        <div class="col-md-6 con">
            <a href="{% url 'social:begin' 'facebook' %}" class="connect facebook">
              <div class="connect__icon">
                <i class="fa fa-facebook"></i>
              </div>
              <div class="connect__context">
                <span>Sign in with <strong>Facebook</strong></span>
              </div>
            </a>
        </div>
        <div class="col-md-6 con">
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="connect googleplus">
              <div class="connect__icon">
                <i class="fa fa-google-plus"></i>
              </div>
              <div class="connect__context">
                <span>Sign in with <strong>Google+</strong></span>
              </div>
            </a>
        </div>
        </div>
    </div>

      </div>
    </div>
  </div>
</div>
     {% if error_message %}
            <script>
            alert('{{ error_message }}')
            </script>
            {% endif %}
{% endblock %}

hostingportal/templates/hostingportal/password.html
{% extends 'hostingportal/base_clientportal.html' %}

{% block body %}
  <h2>Change Password</h2>
  {% if not user.has_usable_password %}
    <p style="color: red">You have not defined a password yet.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock %}